Feature/group permissions
Open-MBEE/mms pull request #192
Opened 2022-06-15 23:31 UTC by Enquier

This PR adds more control over the management and creation of groups, it also refactors the UserDetails service to provide a more abstract users api

2022-06-23 19:59 UTC, HuiJun commented
Firstly, I think we should discuss why this is needed at all. I think originally, we wanted as much abstraction with 'groups' as possible and let whichever authentication implementation handle it however it wanted. Secondly, would such fine grained authorization even be necessary, as we can just let an 'admin' user do whatever he wanted. It just seems like a lot of overhead just to allow fine grained control of an object we don't even want to manage in the first place. Lastly, a local and remote user could easily be differentiated by whether a password is set or not, so mangling the data structure doesn't seem to be necessary there either. I think a better approach might be to just remove the 'syncing' of user and groups altogether. Anyways, further discussion is needed before more work is done here.

2022-06-28 05:29 UTC, dlamoris requested changes
first pass

2022-06-28 05:29 UTC, dlamoris commented on permissions/src/main/java/org/openmbee/mms/permissions/config/PermissionInit.java
> +            evGroup.getUsers().addAll(userRepo.findAll());
i would rather not have to maintain all users to the everyone group, i think everyone can be injected into the core security check like org.openmbee.mms.core.utils.AuthenticationUtils

2022-06-28 05:29 UTC, dlamoris commented on data/src/main/java/org/openmbee/mms/data/domains/global/Group.java
> +    @JoinTable(name = "users_groups", joinColumns = @JoinColumn(name = "users_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "groups_id", referencedColumnName = "id"))
the column names should match current (user_id and group_id) to minimize db migration

2022-06-28 05:29 UTC, dlamoris commented on data/src/main/java/org/openmbee/mms/data/domains/global/Group.java
> +    private VALID_GROUP_TYPES type;
why is both type and typeString needed?

2022-06-28 05:29 UTC, dlamoris commented on data/src/main/java/org/openmbee/mms/data/domains/global/User.java
> +    @JoinTable(name = "users_groups", joinColumns = @JoinColumn(name = "users_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "groups_id", referencedColumnName = "id"))
avoid changing existing column names

2022-06-28 05:29 UTC, dlamoris commented on data/src/main/java/org/openmbee/mms/data/domains/global/User.java
> +    public enum VALID_USER_TYPES {LOCAL, REMOTE}
we currently distinguish local vs remote user by empty password, which should be sufficient

2022-06-28 05:29 UTC, dlamoris commented on docker-compose.yml
> +  # mms:
?
this is needed for the ci tests to work

2022-06-28 05:29 UTC, dlamoris commented on ldap/src/main/java/org/openmbee/mms/ldap/security/LdapAuthoritiesConfig.java
> +                Optional<Group> evGroup = getGroupRepo().findByName(AuthorizationConstants.EVERYONE);
I think the addGroups wasn't supposed to be here - for ldap/remote users we don't want to sync the groups relationships, only to return the right authorities based on the groups mms already has, if a user is added to a local group doing this will reset those relationships
lines 117 to 125 can be deleted
instead, it can find any local group relationship and add them to memberGroups, that's where the authorities are populated from

2022-06-28 05:29 UTC, dlamoris commented on ldap/src/main/java/org/openmbee/mms/ldap/security/LdapAuthoritiesConfig.java
> +        Optional<Group> evGroup = getGroupRepo().findByName(AuthorizationConstants.EVERYONE);
i don't think adding everyone relationships is needed, see other comment about doing it in org.openmbee.mms.core.utils.AuthenticationUtils

2022-06-28 05:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/GroupGroupPermRepository.java
> +    Optional<GroupGroupPerm> findByGroupAndGroup(Group b, Group group);
i don't think this would work, should be findByGroupAndGroupPerm

2022-06-28 05:29 UTC, dlamoris commented on settings.gradle
> +include 'users'
shouldn't be needed?

2022-06-28 18:43 UTC, Enquier commented on data/src/main/java/org/openmbee/mms/data/domains/global/User.java
> +    public enum VALID_USER_TYPES {LOCAL, REMOTE}
Closing this as the preference stated at the Meeting was to keep this definition

2022-06-28 18:43 UTC, Enquier commented on docker-compose.yml
> +  # mms:
Accidental from my own testing, I will fix this

2022-06-28 18:44 UTC, Enquier commented on ldap/src/main/java/org/openmbee/mms/ldap/security/LdapAuthoritiesConfig.java
> +                Optional<Group> evGroup = getGroupRepo().findByName(AuthorizationConstants.EVERYONE);
In response to the discussion I have removed the syncing of group membership from the LDAP Authorities config

2022-06-28 18:44 UTC, Enquier commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/GroupGroupPermRepository.java
> +    Optional<GroupGroupPerm> findByGroupAndGroup(Group b, Group group);
Removed

2022-06-28 18:45 UTC, Enquier commented on settings.gradle
> +include 'users'
fixed

2022-06-28 18:48 UTC, Enquier commented on ldap/src/main/java/org/openmbee/mms/ldap/security/LdapAuthoritiesConfig.java
> +        Optional<Group> evGroup = getGroupRepo().findByName(AuthorizationConstants.EVERYONE);
I think that's what was done before. I think my primary thought there was having an "everyone" group to allow assigning permissions to "everyone", I'm not sure if that is the exact same use case as "public" but I remember it wasn't working in our MMS4 tests. We could probably do both but not track the "everyone" membership like we do with remote groups

2022-06-28 18:57 UTC, HuiJun commented on users/src/main/java/org/openmbee/mms/users/controller/UsersController.java
> +    @GetMapping(value = "/whoami")
I think this is probably the same information given back on users?user=USERID

2022-06-28 21:50 UTC, Enquier commented on data/src/main/java/org/openmbee/mms/data/domains/global/Group.java
> +    @JoinTable(name = "users_groups", joinColumns = @JoinColumn(name = "users_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "groups_id", referencedColumnName = "id"))
fixed

2022-06-28 21:50 UTC, Enquier commented on data/src/main/java/org/openmbee/mms/data/domains/global/User.java
> +    @JoinTable(name = "users_groups", joinColumns = @JoinColumn(name = "users_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "groups_id", referencedColumnName = "id"))
fixed

2022-06-28 21:51 UTC, Enquier commented on ldap/src/main/java/org/openmbee/mms/ldap/security/LdapAuthoritiesConfig.java
> +        Optional<Group> evGroup = getGroupRepo().findByName(AuthorizationConstants.EVERYONE);
I went through and changed the Everyone group to "remote" and removed all of the user sync stuff. I then re-added the simpleAuthorityGrant for Everyone

2022-06-28 21:52 UTC, Enquier commented on users/src/main/java/org/openmbee/mms/users/controller/UsersController.java
> +    @GetMapping(value = "/whoami")
So this is a little different in that it is getting the userId from the token, i.e. it is telling you who is logged in, something that is very useful for VE and other webapps

2022-06-28 22:09 UTC, Enquier commented on data/src/main/java/org/openmbee/mms/data/domains/global/Group.java
> +    private VALID_GROUP_TYPES type;
type is an enum, typeString lets you set where the source is, basically if typeString isn't "local" the group is REMOTE but the individual auth systems can set type to be "ldap" or "twc"

2022-08-12 19:42 UTC, Enquier commented on permissions/src/main/java/org/openmbee/mms/permissions/config/PermissionInit.java
> +            evGroup.getUsers().addAll(userRepo.findAll());
Resolved. Removed Everyone Group

2024-04-17 15:52 UTC, closed without merging