Testing Merge
Open-MBEE/mms pull request #259
Opened 2024-02-07 08:16 UTC by HuiJun

2024-02-13 04:29 UTC, dlamoris requested changes
have not went over permissions related changes yet
things to check:
- some performance optimizations in federated classes where it's getting entire commit json instead of just commit info from db
- updating deleted elements, deleted key in json
- series of inits across sub/superclasses during element get/post, check logic if element post has deletes as well as updates

2024-02-13 04:29 UTC, dlamoris commented on core/src/main/java/org/openmbee/mms/core/dao/NodePersistence.java
> +    NodeGetInfo findById(String elementId, String refId, String commitId, String id);
first argument is projectId, last argument is elementId

2024-02-13 04:29 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoNodeService.java
> -        node.setNodeType(cameoHelper.getNodeType(element).getValue());
check

2024-02-13 04:29 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoNodeService.java
> +        String commitId = params.getOrDefault(CameoConstants.COMMITID, null);
commitId is a generic request param, not cameo specific one

2024-02-13 04:29 UTC, dlamoris commented on view/src/main/java/org/openmbee/mms/view/controllers/VeController.java
> +        try {
check

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/node/NodeDAOImpl.java
> +                throw new NotFoundException("Key value was null");
transaction?

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/branch/BranchDAOImpl.java
> +            if(!Constants.MASTER_BRANCH.equals(branch.getBranchId())) {
check

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/ProjectDAOImpl.java
> +            logger.error("Could not delete project from project Repository");
should throw error?

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/ProjectDAOImpl.java
> +        } catch (SQLException ex) {
should throw error?

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/config/DatabaseDefinitionService.java
> +            logger.error(e.getLocalizedMessage());
duplicate log?

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/config/DatabaseDefinitionService.java
> -        try (Connection conn = crudDataSources.getDataSource(project).getConnection()) {
check

2024-02-13 04:29 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/config/DatabaseDefinitionService.java
> -    private static final String INITIAL_REF = "INSERT INTO branches (id, branchid, branchname, tag, deleted, timestamp) VALUES (0, 'master', 'master', false, false, NOW());";
creating master branch moved to defaultProjectService

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                    if (json.getCreator() == null || json.getCreator().isEmpty()) {
modified? for update

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                                        new Rejection(json, 403, "No permission to move project org"));
missing continue?

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                                    permissionService.setProjectInherit(false, json.getProjectId());
these should be done after line 162 where project moves org

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +        if(!isProjectIdValid(projectId)) {
the mss check should already take care of this

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/domain/NodeChangeDomain.java
> +        //TODO Probably don't need this (see method below)
don't need?

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        super(nodeGetDomain, commitDomain, nodeUpdateFilters);
should pass getDomain, don't need nodeGetDomain

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/domain/DefaultNodeUpdateFilter.java
> +            if (Constants.TRUE.equals(existing.getIsDeleted()) || isUpdated(updated, existing, info)) {
check resurrecting a deleted element, existing.getIsDeleted won't come from json? it used to be on Node
this comes from FederatedNodeChangeDomain.processElementUpdated, remove the 'deleted' key before doing diffUpdateJson

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +        for (CommitJson commit: refCommits) {
this can potentially be a performance hit as federated was just getting from db and not the entire commit json

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +        List<CommitJson> commits = commitPersistence.findAllByProjectId(projectId);
this can be expensive since it's now getting all json and not just db

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +        if (refJsonOptional.get().isDeleted()) {
check if deleted branch status gets saved in json

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> -        Optional<Branch> branchesOption = this.branchRepository.findByBranchId(branch.getId());
need to port this, or fix branch update/resurrection, see comment below

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +            nodePersistence.branchElements(parentRefOption.get(), parentCommit.get(), committedBranch);
consolidated entry to create branch latest/from commit

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +                branch.setDeleted(false);
can't just undelete a branch if parent commit may have changed, should ignore update if parent ref/parent commit changes

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultProjectService.java
> +        return projectPersistence.update(project);
if moving org, inherited permissions are handled by caller?

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> -        stream.close();
?

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> -                throw new InternalErrorException("Error writing to stream.");
missing in FederatedNodePersistance.streamAllAtCommit

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +        response.getElements().forEach(v -> v.setRefId(refId));
check cameo, also response needs to set commitId

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> -        response.setCommitId(info.getCommitId());
need this

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +            NodeGetInfo getInfo = nodePersistence.findById(projectId, refId, commitId, id);
why not use the other read?

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +    protected Map<String, ElementJson> convertJsonToMap(List<ElementJson> elements) {
duplicated in JsonDomain

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +    protected List<ElementJson> filter(List<String> ids, List<ElementJson> orig) {
maybe move to JsonDomain

2024-02-13 04:29 UTC, dlamoris commented on groups/src/main/java/org/openmbee/mms/groups/services/GroupValidationService.java
> +        return userGroupsPersistence.findUsersInGroup(group.getName()).isEmpty();
this can be bad if we're not maintaining group/user relationship due to ldap/sso providing groups

2024-02-13 04:29 UTC, dlamoris commented on json/src/main/java/org/openmbee/mms/json/BaseJson.java
> +    public T setIsDeleted(String deleted) {
should check where this is set, used to be Node has deleted info, not element json

2024-02-13 04:29 UTC, dlamoris commented on localuser/src/main/java/org/openmbee/mms/localuser/controllers/LocalUserController.java
> +    @PreAuthorize(AuthorizationConstants.IS_MMSADMIN)
hmm

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedOrgPersistence.java
> +            throw new ForbiddenException("org " + orgJson.getId() + " already exists");
this prevents org update

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedOrgPersistence.java
> +        organization.setOrganizationName(orgJson.getName());
should also set public

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedProjectPersistence.java
> +            throw new NotFoundException(message);
should be internal error

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedProjectPersistence.java
> +        ContextHolder.setContext(projectId);
redundant

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                    json.merge(existingOptional.get());
cannot change schema

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedElementDomain.java
> +        return elementUtils.getNodeType(element).ordinal()+1;
check db

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        commit.setCommitId(commitJson.getDocId());
should be getId? they should be the same anyway, check if commitJson got set correctly

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +    public CommitJson update(CommitJson commitJson) {
this is used by twc module for syncing some twc commit?

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        commits.sort(Comparator.comparing(BaseJson::getCreated));
is this descending or ascending

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        List<CommitJson> commits = commitIndexDAO.findAllById(commitIds);
should check what's calling this if it's better to call commitDao instead if the full json isn't needed

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        ContextHolder.setContext(projectId);
called from DefaultCommitService, commitDocIds is passed in but was gotten from full json, CommitPersistence should use this without passing in commitDocIds as interface instead, interface should be elementHistory(projectid, refid, elementid)

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        throw new NotFoundException("Could not delete commit");
this is used for cleaning up failed commit save, but throwing exception here just throws it into catch block of caller

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +            resJson.addAll(commits);
this used to not include commit element details in the return, may need some tests with mdk

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/branches/BranchesController.java
> +                        res = branchService.updateBranch(projectId, branch);
shoudln't just merge if parent ref or parent commit is changing

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +       return branchPersistence.update(branch);
federated branch persistence just calls save which assumes branch is a new branch

2024-02-13 04:29 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +            cmjs.setCommitId(commitId);
this sets _commitId instead of id (but id gets overwritten by downstream anyways

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedNodePersistence.java
> +                Collection<ElementJson> result = getNodeGetDomain().processGetJsonFromNodes(ns, commitId)
processGetJsonFromNodes behave differently if commitId is null, this should be passed null if latest to prevent commit behavior, the caller currently always passed in commitId, even if latest

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +        return nodeGetInfo;
- fix existingNodeMap here, also set element RefId?

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +            List<Node> existingNodes = nodeDAO.findAllByNodeIds(elementIds);
should do in caller and not here, federated caller should already have the nodes

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +    public void addExistingElements(NodeChangeInfo nodeChangeInfo, List<ElementJson> existingElements) {
not used anywhere

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +                rejectDeleted(info, nodeId, indexElement);
indexElement can be null?

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +            ElementJson indexElement = info.getExistingElementMap().get(nodeId);
indexElement can be null, see previous code in NodeGetHelper

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +                    addActiveElement(info, nodeId, tryExact.get());
set refId

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +                    addActiveElement(info, nodeId, e.get());
set refid

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +        List<CommitJson> refCommits = commitPersistence.findByProjectAndRefAndTimestampAndLimit(getContext().getProjectId(), getContext().getBranchId(), time, 0);
this should use db dao instead of commitPersistence for performance

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +    private CommitPersistence commitPersistence;
use commitdao insetad of commitPersistence to prevent unnecessary commit json gets

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedNodePersistence.java
> +        return getNodeGetDomain().processGetJson(elements, commitId);
commitId is never null, passed in from DefaultNodeService, processGetJson will never use performant get for latest

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        NodeChangeInfo info =  super.initInfo(commitJson, overwrite, preserveTimestamps);
should fix constructor to have correct nodeGetDomain init

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +            reqElementMap.putAll(convertJsonToMap(transactedElements.parallelStream().collect(Collectors.toList())));
fix convertJsonToMap signature so it doesn't need list

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +                info.addRejection(element.getId(), new Rejection(element, 500, "Update failed: previous element not found"));
should allow update see NodePostHelper

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        node.setInitialCommit(element.getDocId());
wrong id

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        super.processElementUpdated(info, element, existing);
element may not actually be updated and shouldn't have a commit entry

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedNodePersistence.java
> +        primeNodeChangeInfo(info, jsons);
primeNodeChangeInfo can have already been called if this is element update that includes both updates and deletes, calling this again resets some things in info

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +                existing.setIsDeleted(Constants.TRUE);
this is used in DefaultNodeUpdateFilter, but will get merged into update element, need to remove before merging

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +            ElementJson indexElement = info.getExistingElementMap().get(nodeId);
indexElement can be null

2024-02-13 04:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        if(n != null) {
remove

2024-02-13 04:29 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoViewService.java
> +    public void extraProcessPostedElement(NodeChangeInfo info, ElementJson element) {
there shouldn't be any _childViews posted starting with ve 5, can indicate incompatibility with ve < 5  going forward

2024-02-13 04:29 UTC, dlamoris commented on ldap/src/main/java/org/openmbee/mms/ldap/LdapSecurityConfig.java
> +                Set<GroupJson> addGroups = new HashSet<>();
actually don't need to be syncing local db with ldap groups, this can be taken out , just the granted authority (and token) need to have the groups

2024-02-13 04:29 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoViewService.java
> +        ElementsResponse res = this.read(projectId, refId, buildRequestFromJsons(groups), params);
groups already is the right list of json

2024-02-13 04:29 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoViewService.java
>      public ElementsResponse getGroups(String projectId, String refId, Map<String, String> params) {
add override

2024-02-13 19:19 UTC, HuiJun commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +        res.getCommits().addAll(commitPersistence.elementHistory(projectId, elementId, commitIds));
*

2024-02-13 19:21 UTC, HuiJun commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +        List<CommitJson> commits = commitPersistence.findAllByProjectId(projectId);
*

2024-02-13 19:24 UTC, HuiJun commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        super(nodeGetDomain, commitDomain, nodeUpdateFilters);
*

2024-02-13 22:49 UTC, dlamoris commented on core/src/main/java/org/openmbee/mms/core/dao/NodePersistence.java
> +    NodeGetInfo findById(String elementId, String refId, String commitId, String id);
fixed in https://github.com/Open-MBEE/exec-mms/pull/260

2024-02-13 22:57 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoNodeService.java
> -        node.setNodeType(cameoHelper.getNodeType(element).getValue());
this was replaced by https://github.com/Open-MBEE/exec-mms/blob/feature/persistence_refactor/federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java#L140

2024-02-13 23:13 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                                        new Rejection(json, 403, "No permission to move project org"));
fixed in #260

2024-02-14 00:09 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        super(nodeGetDomain, commitDomain, nodeUpdateFilters);
fixed in #260

2024-02-14 00:21 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +        for (CommitJson commit: refCommits) {
fixed in #260

2024-02-14 00:27 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultCommitService.java
> +        List<CommitJson> commits = commitPersistence.findAllByProjectId(projectId);
fixed in #260

2024-02-14 00:45 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> -        response.setCommitId(info.getCommitId());
fixed in #260

2024-02-14 00:49 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +            NodeGetInfo getInfo = nodePersistence.findById(projectId, refId, commitId, id);
fixed in #260

2024-02-14 00:55 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +    protected Map<String, ElementJson> convertJsonToMap(List<ElementJson> elements) {
fixed in #260

2024-02-14 00:55 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +    protected List<ElementJson> filter(List<String> ids, List<ElementJson> orig) {
fixed in #260

2024-02-14 01:25 UTC, dlamoris commented on json/src/main/java/org/openmbee/mms/json/BaseJson.java
> +    public T setIsDeleted(String deleted) {
deleted key should at least have _ prefix so it doesn't interfere with mdk and other tools thinking it's a valid key

2024-02-14 01:26 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        super.processElementUpdated(info, element, existing);
fixed in #260

2024-02-14 01:30 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        node.setInitialCommit(element.getDocId());
fixed in #260

2024-02-14 01:31 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        NodeChangeInfo info =  super.initInfo(commitJson, overwrite, preserveTimestamps);
fixed in #260

2024-02-14 01:33 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +        if(n != null) {
fixed in #260

2024-02-14 01:35 UTC, dlamoris commented on json/src/main/java/org/openmbee/mms/json/BaseJson.java
> +    public T setIsDeleted(String deleted) {
fixed in #260

2024-02-14 06:17 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +    private CommitPersistence commitPersistence;
fixed in #260

2024-02-14 06:17 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +        return nodeGetInfo;
fixed in #260

2024-02-14 06:17 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +        List<CommitJson> refCommits = commitPersistence.findByProjectAndRefAndTimestampAndLimit(getContext().getProjectId(), getContext().getBranchId(), time, 0);
fixed in #260

2024-02-14 06:18 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +            List<Node> existingNodes = nodeDAO.findAllByNodeIds(elementIds);
fixed in #260

2024-02-15 21:03 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +            reqElementMap.putAll(convertJsonToMap(transactedElements.parallelStream().collect(Collectors.toList())));
fixed in #260

2024-02-21 19:37 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoNodeService.java
> +        String commitId = params.getOrDefault(CameoConstants.COMMITID, null);
fixed in #260

2024-02-21 20:34 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +                branch.setDeleted(false);
fixed in #260

2024-02-21 20:34 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> -        Optional<Branch> branchesOption = this.branchRepository.findByBranchId(branch.getId());
fixed in #260

2024-02-21 22:06 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedOrgPersistence.java
> +            throw new ForbiddenException("org " + orgJson.getId() + " already exists");
fixed in #260

2024-02-21 22:32 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                    json.merge(existingOptional.get());
fixed in #260

2024-02-21 22:34 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        commit.setCommitId(commitJson.getDocId());
fixed in #260

2024-02-21 22:40 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        commits.sort(Comparator.comparing(BaseJson::getCreated));
fixed in #260

2024-02-22 02:39 UTC, dlamoris commented on cameo/src/main/java/org/openmbee/mms/cameo/services/CameoViewService.java
> +        ElementsResponse res = this.read(projectId, refId, buildRequestFromJsons(groups), params);
fixed in #260

2024-02-22 19:38 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        List<CommitJson> commits = commitIndexDAO.findAllById(commitIds);
is ok

2024-02-22 19:38 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        ContextHolder.setContext(projectId);
fixed in #260

2024-02-22 19:39 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/branches/BranchesController.java
> +                        res = branchService.updateBranch(projectId, branch);
fixed in #260

2024-02-22 19:40 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +       return branchPersistence.update(branch);
fixed in #260

2024-02-22 19:42 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +            cmjs.setCommitId(commitId);
fixed in #260

2024-02-22 19:43 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +    public void addExistingElements(NodeChangeInfo nodeChangeInfo, List<ElementJson> existingElements) {
removed in #260

2024-02-24 09:24 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedNodePersistence.java
> +                Collection<ElementJson> result = getNodeGetDomain().processGetJsonFromNodes(ns, commitId)
fixed in #260 
should check if caller can just pass in null instead...otherwise there's still redundant checks to see if commit is latest

2024-02-24 09:37 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedNodePersistence.java
> +        return getNodeGetDomain().processGetJson(elements, commitId);
fixed in #260

2024-02-24 09:38 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +                existing.setIsDeleted(Constants.TRUE);
fixed in #260

2024-02-24 09:39 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/domain/DefaultNodeUpdateFilter.java
> +            if (Constants.TRUE.equals(existing.getIsDeleted()) || isUpdated(updated, existing, info)) {
fixed in #260

2024-02-24 10:18 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultNodeService.java
> +        response.getElements().forEach(v -> v.setRefId(refId));
fixed in #260

2024-02-24 10:38 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +                    addActiveElement(info, nodeId, tryExact.get());
fixed in #260, refid is set in nodeServices

2024-02-24 10:38 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +                    addActiveElement(info, nodeId, e.get());
fixed in #260, ref id is set in nodeServices

2024-02-24 17:51 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +                info.addRejection(element.getId(), new Rejection(element, 500, "Update failed: previous element not found"));
fixed in #260

2024-02-24 17:59 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +                rejectDeleted(info, nodeId, indexElement);
fixed in #260

2024-02-24 17:59 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeGetDomain.java
> +            ElementJson indexElement = info.getExistingElementMap().get(nodeId);
fixed in #260

2024-02-24 18:06 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedElementDomain.java
> +        return elementUtils.getNodeType(element).ordinal()+1;
ok

2024-02-24 18:47 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedOrgPersistence.java
> +        organization.setOrganizationName(orgJson.getName());
nevermind public is set by permissions

2024-02-24 18:51 UTC, dlamoris commented on view/src/main/java/org/openmbee/mms/view/controllers/VeController.java
> +        try {
fixed in #260 think this was because the added commit check done during read

2024-02-24 19:02 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/branch/BranchDAOImpl.java
> +            if(!Constants.MASTER_BRANCH.equals(branch.getBranchId())) {
ok

2024-02-24 19:24 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/ProjectDAOImpl.java
> +            logger.error("Could not delete project from project Repository");
fixed in #260

2024-02-24 19:24 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/repositories/ProjectDAOImpl.java
> +        } catch (SQLException ex) {
fixed in #260

2024-02-24 20:04 UTC, dlamoris commented on rdb/src/main/java/org/openmbee/mms/rdb/config/DatabaseDefinitionService.java
> -        try (Connection conn = crudDataSources.getDataSource(project).getConnection()) {
ok, master creation moved to default project service

2024-02-24 21:15 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/controllers/projects/ProjectsController.java
> +                                    permissionService.setProjectInherit(false, json.getProjectId());
fixed in #260

2024-02-24 21:49 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultProjectService.java
> +        return projectPersistence.update(project);
org move permission updates are in controller

2024-02-24 21:50 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedProjectPersistence.java
> +            throw new NotFoundException(message);
fixed in #260

2024-02-24 21:51 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/domain/FederatedNodeChangeDomain.java
> +            ElementJson indexElement = info.getExistingElementMap().get(nodeId);
fixed in #260

2024-03-18 21:28 UTC, dlamoris commented on core/src/main/java/org/openmbee/mms/core/services/DefaultPermissionService.java
> +                    RefJson b = new RefJson();
before was only creating global branch, check what side effects using persistence.save have

2024-03-18 22:05 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/DefaultBranchPermissionsDelegate.java
> +                    if (pair == null) {
check return

2024-03-18 22:05 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/DefaultBranchPermissionsDelegate.java
> +                    if (pair == null) {
check return

2024-03-19 02:19 UTC, dlamoris commented on permissions/src/main/java/org/openmbee/mms/permissions/delegation/DefaultPermissionsDelegateFactory.java
> -package org.openmbee.mms.permissions.delegation;
moved into federated module

2024-03-21 04:26 UTC, dlamoris commented on ldap/src/main/java/org/openmbee/mms/ldap/LdapSecurityConfig.java
> +                Set<GroupJson> addGroups = new HashSet<>();
will fix in a separate issue/pr

2024-03-25 17:59 UTC, dlamoris commented on core/src/main/java/org/openmbee/mms/core/services/DefaultPermissionService.java
> +                    RefJson b = new RefJson();
fixed in #260

2024-03-26 00:29 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/DefaultOrgPermissionsDelegate.java
> +    public boolean hasGroupPermissions(String group, String privilege) {
this is actually not used anywhere, just here to fulfill an interface

2024-03-26 00:32 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/AbstractDefaultPermissionsDelegate.java
> +            return null;
line 67 should keep the returned instance

2024-03-26 00:32 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/AbstractDefaultPermissionsDelegate.java
> +            return null;
fixed in #206

2024-03-30 23:56 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/FederatedPermissionUpdatesResponseBuilder.java
> +    public FederatedPermissionUpdatesResponseBuilder setInherit(Boolean inherit) {
setInherit, setPublic, insert functions are never called on this class, only on parent class, can be removed

2024-03-30 23:56 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/FederatedPermissionUpdatesResponseBuilder.java
> +    public FederatedPermissionUpdatesResponseBuilder setInherit(Boolean inherit) {
fixed in #260

2024-03-30 23:57 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/FederatedPermissionsUpdateResponseBuilder.java
> +package org.openmbee.mms.federatedpersistence.permissions;
these were functions from PermissionsUpdateResponseBuilder that uses the DB classes

2024-03-30 23:58 UTC, dlamoris commented on core/src/main/java/org/openmbee/mms/core/builders/PermissionUpdateResponseBuilder.java
> -    public void insertPermissionUpdates_OrgUserPerm(PermissionUpdateResponse.Action action, Collection<OrgUserPerm> perms) {
these are moved to federated module

2024-03-31 00:00 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/DefaultProjectPermissionsDelegate.java
> +    public boolean hasGroupPermissions(String group, String privilege) {
never called, just implements interface

2024-03-31 00:01 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/permissions/DefaultProjectPermissionsDelegate.java
> +    public PermissionResponse getInherit() {
never called

2024-03-31 03:04 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/domain/NodeChangeDomain.java
> +        //TODO Probably don't need this (see method below)
removed in #260

2024-03-31 03:08 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +        if (refJsonOptional.get().isDeleted()) {
yes

2024-03-31 03:20 UTC, dlamoris commented on crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java
> +            nodePersistence.branchElements(parentRefOption.get(), parentCommit.get(), committedBranch);
fixed in #260

2024-03-31 03:49 UTC, dlamoris commented on localuser/src/main/java/org/openmbee/mms/localuser/controllers/LocalUserController.java
> +    @PreAuthorize(AuthorizationConstants.IS_MMSADMIN)
user read should not be restricted to admin, reverted in #260

2024-03-31 04:24 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedCommitPersistence.java
> +        throw new NotFoundException("Could not delete commit");
fixed in #260

2024-03-31 05:51 UTC, dlamoris commented on federatedpersistence/src/main/java/org/openmbee/mms/federatedpersistence/dao/FederatedNodePersistence.java
> +        primeNodeChangeInfo(info, jsons);
changed in #260 to not reinit but add to existing data in info

2024-04-09 17:45 UTC, merged